# Build pipeline
name: "Terraform Build Pipeline for private dns zone"

trigger: 
- main

pr: none

parameters:
  - name: ModuleName
    displayName: 'Module Name'
    default: "private-dns-zone"
    type: string

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName: Clean Checkout
  clean: true

- script: |
     ls -a
     Version=$(cat ./metadata.yml | awk '/version:/ {print $2}')
     echo "##vso[task.setvariable variable=Version]$Version"
     echo $Version
  displayName: 'Fetch Version From Metadata'      

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.SourcesDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'atisha/atisha-terraform'
    vstsFeedPackagePublish: '${{ parameters.ModuleName }}'
    versionOption: 'custom'
    versionPublish: '$(Version)'
    packagePublishDescription: "private-dns-zone terraform package"
    verbosity: 'Error'
    publishedPackageVar: "private-dns-zone creation output"
